[phases.setup]
nixPkgs = ["nodejs_18", "bun"]
aptPkgs = [
  "libx11-xcb1","libnss3","libatk1.0-0","libatk-bridge2.0-0","libxss1","libgtk-3-0",
  "libasound2","libxshmfence1","libgbm1","libglu1-mesa","libpangocairo-1.0-0",
  "libxrandr2","libxcomposite1","libxcursor1","libxi6","libxdamage1",
  "libx11-6","libxcb1","libxext6","libxfixes3"
]
