
import React from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { FileText, AlertCircle, Users, Gavel, Globe } from 'lucide-react';

const Terms = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-tech-gray-50 via-white to-tech-neon/5 font-sans">
      <Header />
      
      <main className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto">
          {/* Hero Section */}
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold text-tech-dark mb-6">
              Terms of Service
            </h1>
            <p className="text-xl text-tech-gray-600 max-w-2xl mx-auto">
              The rules and conditions that govern the use of Is it Better?
            </p>
          </div>

          <div className="space-y-8">
            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <FileText className="h-5 w-5 text-tech-electric" />
                  <span>Agreement to Terms</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-tech-gray-700 mb-4">
                  By accessing and using Is it Better? ("Service"), you agree to be bound by these Terms of Service ("Terms"). 
                  If you disagree with any part of these terms, you may not use our Service.
                </p>
                <div className="bg-tech-electric/10 p-4 rounded-lg">
                  <p className="text-sm text-tech-gray-700">
                    <strong>Important:</strong> These Terms may be updated from time to time. Changes become effective 
                    immediately upon posting. Your continued use of the Service constitutes acceptance of the revised Terms.
                  </p>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Users className="h-5 w-5 text-tech-electric" />
                  <span>Acceptable Use</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Permitted Uses</h4>
                    <ul className="text-tech-gray-700 space-y-1">
                      <li>• Compare two technology products for personal or business decision-making</li>
                      <li>• Access AI-powered recommendations and insights</li>
                      <li>• Share comparison results with others</li>
                      <li>• Use the Service for educational or research purposes</li>
                    </ul>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Prohibited Uses</h4>
                    <ul className="text-tech-gray-700 space-y-1">
                      <li>• Use automated systems (bots, scripts) to access the Service</li>
                      <li>• Attempt to reverse engineer or extract our algorithms</li>
                      <li>• Submit false, misleading, or malicious data</li>
                      <li>• Use the Service for illegal activities or to violate others' rights</li>
                      <li>• Attempt to overwhelm our systems or disrupt service availability</li>
                      <li>• Resell or redistribute our Service without authorization</li>
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <AlertCircle className="h-5 w-5 text-tech-electric" />
                  <span>Disclaimers & Limitations</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="bg-amber-50 border border-amber-200 p-4 rounded-lg">
                    <h4 className="font-semibold text-amber-800 mb-2">Important Disclaimer</h4>
                    <p className="text-amber-700 text-sm">
                      Is it Better? provides information and recommendations generated by artificial intelligence for informational 
                      purposes only. Results should not be considered as professional advice.
                    </p>
                  </div>
                  
                  <div className="grid md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <h4 className="font-semibold text-tech-dark">No Warranties</h4>
                      <p className="text-sm text-tech-gray-600">
                        The Service is provided "as is" without warranties of any kind, either express or implied, 
                        including but not limited to accuracy, completeness, or fitness for a particular purpose.
                      </p>
                    </div>
                    <div className="space-y-2">
                      <h4 className="font-semibold text-tech-dark">Limitation of Liability</h4>
                      <p className="text-sm text-tech-gray-600">
                        We shall not be liable for any indirect, incidental, special, or consequential damages 
                        resulting from your use of the Service.
                      </p>
                    </div>
                    <div className="space-y-2">
                      <h4 className="font-semibold text-tech-dark">Third-Party Data</h4>
                      <p className="text-sm text-tech-gray-600">
                        Product specifications may come from third-party sources. We strive for accuracy but 
                        recommend verifying information with manufacturers.
                      </p>
                    </div>
                    <div className="space-y-2">
                      <h4 className="font-semibold text-tech-dark">Service Availability</h4>
                      <p className="text-sm text-tech-gray-600">
                        We do not guarantee uninterrupted or error-free service operation. 
                        Maintenance and updates may temporarily affect availability.
                      </p>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Gavel className="h-5 w-5 text-tech-electric" />
                  <span>Intellectual Property</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Our Content</h4>
                    <p className="text-tech-gray-700">
                      The Service, including its design, features, algorithms, and user interface, is protected by copyright, 
                      trademark, and other intellectual property laws. All rights are reserved.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">User-Generated Content</h4>
                    <p className="text-tech-gray-700">
                      By submitting data or content to our Service, you grant us a non-exclusive, worldwide, royalty-free 
                      license to use, modify, and display such content solely for providing and improving our Service.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Third-Party Trademarks</h4>
                    <p className="text-tech-gray-700">
                      Product names, logos, and trademarks displayed in our Service belong to their respective owners. 
                      We do not claim ownership of these marks.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Globe className="h-5 w-5 text-tech-electric" />
                  <span>International Use & Governing Law</span>
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Global Accessibility</h4>
                    <p className="text-tech-gray-700">
                      Our Service is accessible worldwide, but we make no representation that it complies with 
                      laws in all jurisdictions. Users are responsible for compliance with local laws.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Governing Law</h4>
                    <p className="text-tech-gray-700">
                      These Terms shall be governed by and construed in accordance with international commercial law principles. 
                      Disputes shall be resolved through binding arbitration.
                    </p>
                  </div>
                  
                  <div>
                    <h4 className="font-semibold text-tech-dark mb-2">Severability</h4>
                    <p className="text-tech-gray-700">
                      If any provision of these Terms is found to be unenforceable, the remaining provisions 
                      shall remain in full force and effect.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200">
              <CardHeader>
                <CardTitle>Account Termination & Suspension</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-tech-gray-700 mb-4">
                  We reserve the right to suspend or terminate access to our Service, with or without notice, for users who:
                </p>
                <ul className="text-tech-gray-700 space-y-1 mb-4">
                  <li>• Violate these Terms of Service</li>
                  <li>• Engage in abusive or harmful behavior</li>
                  <li>• Compromise the security or performance of our Service</li>
                  <li>• Use the Service for illegal purposes</li>
                </ul>
                <p className="text-tech-gray-700">
                  Upon termination, your right to use the Service ceases immediately. 
                  We may delete any data associated with your use of the Service.
                </p>
              </CardContent>
            </Card>

            <Card className="shadow-lg border-tech-gray-200 bg-gradient-to-r from-tech-electric/5 to-tech-neon/5">
              <CardContent className="p-6">
                <h3 className="font-semibold text-tech-dark mb-3">Contact Information</h3>
                <p className="text-tech-gray-700 mb-3">
                  For questions about these Terms of Service, please contact us at: 
                  <span className="font-semibold text-tech-electric"> legal@isitbetter.com</span>
                </p>
                <p className="text-tech-gray-700 mb-3">
                  For general inquiries: <span className="font-semibold text-tech-electric">contact@isitbetter.com</span>
                </p>
                <p className="text-sm text-tech-gray-600">
                  Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Terms;
